### ISSUE TITLE
Reshaping .npy for prediction

### ISSUE THREAD

**Issue by alexivaner** [olly-styles/Dynamic-Trajectory-Predictor#10]
Hi, I need your help about npy that generated by YOLO, I tried to visualize the result prediction.
![image](https://user-images.githubusercontent.com/57290644/89992104-5fa50e80-dcb7-11ea-91a5-0cb18b90ace8.png)

Why the shape is 
(3843450,)?
Thank you, glad if you could help.

**Comment by olly-styles** [comment]
Hi,

As the output layer is fully connected, the labels are flattened. This happens on this line:  https://github.com/olly-styles/Dynamic-Trajectory-Predictor/blob/eb9b02ae3e77b38d9877824637199effe0a4068e/train_dtp_bdd.py#L102

The format of these labels is [x_vals_sample_1, y_vals_sample_1, ... x_vals_sample_n, y_vals_sample_n]. You can reshape it to (17082, 15, 15), which is (n_samples, x_predictions, y_predictions).

Hope that helps.

**Comment by alexivaner** [comment]
Hi, after reshape, I found that the number is too small for coordinates in the picture right?
and which frames are 17082 stands for?
![image](https://user-images.githubusercontent.com/57290644/90329435-714c2600-dfd7-11ea-9d56-01fa424486e6.png)

and also if we take those labels as  [x_vals_sample_1, y_vals_sample_1, ... x_vals_sample_n, y_vals_sample_n].  The value is odd right? It is only 15 not 16? I am sorry, I still really confuse about this. Glad if you could help, thank you.

**Comment by albertchristian92** [comment]
Hi @olly-styles, I am also curious, why the coordinate result is minus? is it the data normalized? if yes, how much the maximum value before normalized? Thank you for help

**Comment by olly-styles** [comment]
The reshape looks correct. The labels are now in the format (sample, x_labels, y_labels). The model predicts 1 second into the future at 15 FPS, so 15 frames.

Some of the values are less than 0 as the model predicts the constant velocity residual rather than the coordinates directly. See Figure 2 and Section III B of the paper.
