### ISSUE TITLE
 The video

### ISSUE THREAD

**Issue by l123-123** [olly-styles/Dynamic-Trajectory-Predictor#14]
Hi,I want to  use your Dynamic-Trajectory-Predictor  to generate the video  that you post on Youtube

Could you please share your code?

Thank you very much

https : //www.youtube.com/watch?v=jUTQyUjeynE

**Comment by l123-123** [comment]
I don't konw how to use your Dynamic-Trajectory-Predictor to generate the video that you post on Youtube.

**Comment by olly-styles** [comment]
Hi,

Thanks for your interest in our work. Please see my response to Issue #5 regarding visualiation.
