### ISSUE TITLE
Ego motion free trajectories

### ISSUE THREAD

**Issue by atanas1054** [olly-styles/Dynamic-Trajectory-Predictor#3]
Hello,

Have you considered extracting ego motion free pedestrian trajectories for future work? Currently your model learns the ego motion implicitly as well.

I was thinking of something like multimotion visual odometry (MVO) which can separate the motion of the ego vehicle and that of the pedestrians. Any thoughts on this?

**Comment by olly-styles** [comment]
Yes, the model learns ego-motion and object motion jointly. MVO could be a nice solution for separating the two motions.
