### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Kamel-schbock** [olly-styles/Dynamic-Trajectory-Predictor#5]
hey, 
After training and testing how can i see the results as visualization?
Video_transforms.py contains the visualization part as the video on youtube?
thanks

**Comment by olly-styles** [comment]
Hi, thanks for your interest in our work.

The video_transforms file contains data augmentations for video data. It doesn't contain and visualization code.

We visualized the trajectories using the Open-CV drawing functions, in particular cv2.line. I'm afraid we won't be releasing the visualization code.

**Comment by Kamel-schbock** [comment]
Hi,
Thank for for answering my question.
I am student and i want to extend your project for (uncertainty aware) in my thesis.
That's why, i am asking you about the visualization. 
If you don't want to release on github for some reasons, i will be glad if you can share it with me via email and i will make off course a citation of yours  in my work.
If not, thanks in all cases😊 
Best regards
