### ISSUE TITLE
Questions about Metrics

### ISSUE THREAD

**Issue by trungmanhhuynh** [olly-styles/Dynamic-Trajectory-Predictor#6]
Hi Olly,
Thanks for the work. I have a question about the metrics you used (MSE and DE@t) Why the MSE is so large compared to DE@? 

As with my understanding, the MSE is average squared error across on predicted locations, DE@t is the error at time t, which is usually at the final location. Thus, MSE should be usually smaller than DE@t. Could you help clarify this? 

Thanks,

**Comment by olly-styles** [comment]
Hi,
Thanks for the question. Your understanding is correct that the MSE is the average over all timesteps whereas DE@t is for the t th timestep only. The reason MSE is much larger is it is the squared difference between prediction and ground truth, whereas DE@t is the absolute displacement error (i.e. not squared)

Hope that clears things up.

Olly

**Comment by trungmanhhuynh** [comment]
Olly,
Thank you so much for your clarification. It helps a lot.
