### ISSUE TITLE
code bug

### ISSUE THREAD

**Issue by 1187697147** [olly-styles/Dynamic-Trajectory-Predictor#7]
Hi, olly
Haha, it's me again(maybe i will always ask you some questions about your project in the next few weeks).
I find something maybe wrong in your code.
train_dtp_jaad.py(line335) 'optimizer = optim.Adam(model.parameters(), lr=1e-6, **_weight_weight_decay=decay_**)' .

tips:
When i read your code(process_bounding_boxes_jaad.py), i think this line 'for rownum in range(1, len(boxes[**1:**])):' always can't get the last value. Maybe this will not cause any changes, but i think this need to be corrected just for avoiding potential problems.

**Comment by olly-styles** [comment]
Thanks for letting me know! I've fixed the bug.
