### ISSUE TITLE
How to get optical flow?

### ISSUE THREAD

**Issue by 1187697147** [olly-styles/Dynamic-Trajectory-Predictor#8]
Hi, 
I tried to use FlowNet2 to get optical flow frames, but i found that flownet return .flo file, i use cvbase to show picture.
However, i still want to know if FlowNet2 can get the result of your project, because put two images into FlowNet and return only one picture. How can you get two frames(x\y) using flownet?

**Comment by olly-styles** [comment]
Which implementation are you using? I used this one, which returns the flow frames as arrays: https://github.com/NVIDIA/flownet2-pytorch

**Comment by 1187697147** [comment]
I used the same repo of flownet2-pytorch. The command i used to run main.py:
`python main.py --inference 
--model FlowNet2 
--save_flow 
--save PATH_TO_SAVE
--inference_dataset ImagesFromFolder 
--inference_dataset_root MY_PIC_DATA_PATH
--resume PATH_TO/FlowNet2_checkpoint.pth.tar`
After using command above, i can see inference, train, validation, arg.txt in my save_path. Because i use just two pictures  to run, so i get 000000.flo in /inference/run.epoch-0-flow-field. 
I use cvbase to show the result picture, how do you run main.py to get  horizontal and vertical optical flow??

**Comment by olly-styles** [comment]
Check the inference function 

https://github.com/NVIDIA/flownet2-pytorch/blob/2e9e010c98931bc7cef3eb063b195f1e0ab470ba/main.py#L343

Which is run when you use the command main.py --inference. The method gets the optical flow output as a torch tensor before saving it as a .flo file. You can modify the function to convert the torch tensor to a NumPy array and save that instead.

**Comment by 1187697147** [comment]
Ok, do you mean _pflow[:, :, 0] and _pflow[:, :, 1]?
I save this two numpy array using scipy, now i can see two similar image. So, i get the right image???
![test1](https://user-images.githubusercontent.com/23122139/88749009-fab0cb00-d184-11ea-8fb4-5e316ae65191.png)
![test2](https://user-images.githubusercontent.com/23122139/88749021-000e1580-d185-11ea-849d-d3a2ee6dcd40.png)
![result0](https://user-images.githubusercontent.com/23122139/88749027-03090600-d185-11ea-8643-959a071e2928.png)
![result1](https://user-images.githubusercontent.com/23122139/88749029-043a3300-d185-11ea-8696-c87e9bfce802.png)

**Comment by olly-styles** [comment]
It's difficult to tell from the example as there isn't much movement, but the results look reasonable to me. I'm not sure which is horizontal and vertical flow, I suggest either doing your own tests or asking the owners of the FlowNet repo.

**Comment by 1187697147** [comment]
I think so. When there are at least two persons in pictures, you just do some processes to avoid calculating optical flow on such a condition that first frame belongs to person1 and second frame belongs to person2 ?? (or you just handle one person in the picture??)

**Comment by olly-styles** [comment]
We always treat two images as if they contain the same individual. We use a state-of-the-art tracker to minimize identity switching.

**Comment by alexivaner** [comment]
> Ok, do you mean _pflow[:, :, 0] and _pflow[:, :, 1]?
> I save this two numpy arrays using scipy and then see two similar images. So, i get the target images DTP need??which one is vertical optical flow( _pflow[:, :, 0] or _pflow[:, :, 1])??
> ![test1](https://user-images.githubusercontent.com/23122139/88749009-fab0cb00-d184-11ea-8fb4-5e316ae65191.png) ![test2](https://user-images.githubusercontent.com/23122139/88749021-000e1580-d185-11ea-849d-d3a2ee6dcd40.png) ![result0](https://user-images.githubusercontent.com/23122139/88749027-03090600-d185-11ea-8643-959a071e2928.png) ![result1](https://user-images.githubusercontent.com/23122139/88749029-043a3300-d185-11ea-8696-c87e9bfce802.png)
> 
> note: picture3 is _pflow[:, :, 0] and picture4 is _pflow[:, :, 1]

Hi according to this repo:

https://github.com/georgegach/flowiz

![image](https://user-images.githubusercontent.com/57290644/89736000-ed56e300-da98-11ea-9ad0-3510d351ba5f.png)

 _pflow[:, :, 0] is horizontal 
_pflow[:, :, 1] is vertical

**Comment by 1187697147** [comment]
Ok, thanks
