### ISSUE TITLE
The optical flow size of DTP and MOF

### ISSUE THREAD

**Issue by 1187697147** [olly-styles/Dynamic-Trajectory-Predictor#9]
hi,
I also find that optical flows' size DTP used in train_dtp_bdd.py  is **(128,256)**. When load optical flows in LocationDatasetBDD(), the flow_stack's size is **(256,256)**, but your paper seems to use **(244,244)**. So i feel confused about these different size. Namely, which size should i use to save yolov3 detection area? Which size should i use in train_dtp_bdd.py?

**Comment by olly-styles** [comment]
From the paper "Each pedestrian is resized to 256 × 256 pixels. For data augmentation, a randomly cropped sub-image of size 224 × 224 is taken."
